"""
Atlas: A Python package for image processing workflows for images generated by ATLAS (FIBICS).

Submodules:
- io: Handles input/output operations.
- stitching: Image stitching functions.
- alignment: Image alignment functions.
- image_analysis: Image processing and analysis functions.
"""

from . import io
from . import stitching
from . import alignment
from . import image_analysis

__all__ = ["io", "stitching", "alignment", "image_analysis"]