"""
Atlas: A Python package for image processing workflows for images generated by ATLAS (FIBICS).

Submodules:
- io: Handles input/output operations.
- stitching: Image stitching functions.
- alignment: Image alignment functions.
- image_analysis: Image processing and analysis functions.
- misc: General visualization and utility functions.
"""

from . import alignment
from . import image_analysis
from . import io
from . import misc
from . import stitching

__all__ = ["io", "stitching", "alignment", "image_analysis", "misc"]
